### ISSUE TITLE
ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

### ISSUE THREAD

**Issue by sarrbranka** [vasilysinitsin/Faces#14]
after running the code below, i got an error. Any idea?

```

import faces

old_rockfeller = 'https://upload.wikimedia.org/wikipedia/commons/6/6f/John_D._Rockefeller_1885.jpg'
image = faces.FaceAppImage(url=old_rockfeller)
young_rockfeller = image.apply_filter('young')
```

**Comment by vasilysinitsin** [comment]
@sarrbranka, by pure guess I can assume something wrong either with your internet access and permissions or with remote server. Please note that repository is not actively maintained and I'm not about to update it any soon.
