### ISSUE TITLE
How can i get an output file?

### ISSUE THREAD

**Issue by GerardoPrado** [vasilysinitsin/Faces#4]
Hi! great job!
But i cant get an output file, just verify that the filters are working

Cheers

**Comment by UtpalDas6** [comment]
It returns filtered image in byte format... Convert bytes to image and save it.. follow this link
https://stackoverflow.com/questions/18491416/pil-convert-bytearray-to-image

**Comment by vasilysinitsin** [comment]
@GerardoPrado sorry for my late response.
Could you put some code for reference?

**Comment by UtpalDas6** [comment]
Output here is a byte code. Convert byte code into image file and save it to a location.
#code
bytes = readimage(path+extension)
image = Image.open(io.BytesIO(bytes))
image.save(savepath)
