### ISSUE TITLE
How to get output file?

### ISSUE THREAD

**Issue by freke70** [vasilysinitsin/Faces#5]
Hi, Thanks for making this.
Unfortunately I can't get an output file.
I created a py file with htis :+1: 

import faces

sad = open('sad.jpg', 'rb')
image = faces.FaceAppImage(file=sad)
happy = image.apply_filter('smile', cropped=True)
happy.save('/home/user/Face/output.jpg')

But I get this error:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    happy.save('/home/nfrederickx/Face/output.jpg')
AttributeError: 'str' object has no attribute 'save'

I have no idea what I'm doing.

Thanks for helping!

**Comment by vasilysinitsin** [comment]
Hey, @freke70 .
The apply_filter method will return you a standard Python 'bytes' class.
If you need to save image to file, you should create a writable file object in byte mode (wb) and write this bytes there like here:
```
with open('a.jpg', 'wb') as f:
    img=faceapp_image_instanse.apply_filter('smile')
    f.write(img)
```
